apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z3b9q3l97-python
  janus-idp.io/tekton: z3b9q3l97-python
  backstage.io/kubernetes-id: z3b9q3l97-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z3b9q3l97-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
