apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: z3b9q3l97-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: z3b9q3l97-python 
  name: z3b9q3l97-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: z3b9q3l97-python 
