apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: z3b9q3l97-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:d64fe2d186890f89d7b606d2f25ced3676d89f39@sha256:f211b1760b370f4fcc02bbe1d18e30acb45d51ac5f491c2f2f2429a6d9294263
          name: container-image
